version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers
      - image: redis:latest
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev libjpeg-dev libpng-dev
      - run: sudo docker-php-ext-install gd
      #- run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: php artisan storage:link
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpunit
